---
# tasks file for nmap
- name: nmap for get port information 
  block:
  - debug:
      msg: "Generación de reporte con el estado de los puertos"
  
  - set_fact: fecha="{{lookup('pipe','date +%Y%m%d%H%M%S') }}"

  - name: Copy_puertos.csv
    copy: 
      src: nmap/files/puertos.csv
      dest: /tmp
      mode: 444
    tags:
    - copy-puertos.csv
  - debug:
      msg: "Copiando el archivo puertos.csv"

  - name: check port
    script: nmap/files/ports.sh /tmp/puertos.csv {{ fecha  }}
    args:
       chdir: /home/jhernandez/tmp/
    tags:
    - check_port
  - debug:
      msg: "Creando reporte"

  - name: Crea directorio local
    local_action:
      module: file
      path: /tmp/nmap-{{ fecha }}
      state: directory
      mode: 0755
    tags:
    - local_directory
  - debug:
      msg: "Creando directorio local"

  - name: Obtener evidencia 
    fetch:
      flat: yes
      src: /home/jhernandez/tmp/{{ ansible_fqdn }}_scan_{{ fecha }}.csv
      dest: /tmp/nmap-{{ fecha }}/
    tags:
    - local_directory
  - debug:
      msg: "Copiando archivos a /tmp/nmap-{{ fecha }}"

  - name: Eliminando evidencia en servidor remoto 
    file:
      path: /home/jhernandez/tmp/{{ ansible_fqdn }}_scan_{{ fecha }}.csv
      state: absent
    tags:
    - delete_remote
  - debug:
      msg: "Eliminando evidencia en servidor remoto"

  - name: Eliminando archivo de puertos.csv
    file:
      path: /tmp/puertos.csv
      state: absent
    tags:
    - delete_remote
  - debug:
      msg: "Eliminando evidencia en servidor remoto"

  - name: Crea_reporte_conjunto
    local_action:
      module: shell echo "Origen,Destination,Port,Protocol,Service,State" >/tmp/nmap-{{ fecha }}/all.csv && cat /tmp/nmap-{{ fecha }}/*csv  | grep -v "Origen" >> /tmp/nmap-{{ fecha }}/all.csv
    tags:
    - full_report
  - debug:
      msg: "Creando reporte global"