---
# tasks file for nmap
- name: nmap for get port information 
  block:
  - debug:
      msg: "Generación de reporte con el estado de los puertos"
  

  - name: Hora local
    #local_action: set_fact  fecha="{{lookup('pipe','date +%Y%m%d%H%M%S') }}"
    set_fact: 
       fecha: "{{lookup('pipe','date +%Y%m%d%H%M%S') }}"
       cacheable: yes
    run_once: True
    delegate_to: 127.0.0.1
    #delegate_facts: True
  - debug:
      msg: "Se obtiene el tiempo {{ fecha }}"
  
  #- name: Include vars
  #  include_vars: nmap/vars/main.yml 

  - name: Crea directorio local
    #local_action:
    #module: file
    file:
      path: /{{ local_path }}nmap-{{ fecha }}
      state: directory
      mode: 0755
    delegate_to: 127.0.0.1
    tags:
    - local_directory
  - debug:
      msg: "Creando directorio local /{{ local_path }}nmap-{{ fecha }}"

  - name: Copy_puertos.csv
    copy: 
      src: nmap/files/puertos.csv
      dest: /tmp
      mode: 444
    tags:
    - copy-puertos.csv
  - debug:
      msg: "Copiando el archivo puertos.csv"

  - name: check port
    script: nmap/files/ports.sh /tmp/puertos.csv {{ fecha  }}
    args:
       chdir: /{{ remote_path }}
    tags:
    - check_port
  - debug:
      msg: "Creando reporte en /{{ remote_path }}"


  - name: Obtener evidencia 
    fetch:
      flat: yes
      src: /{{ remote_path }}{{ ansible_fqdn }}_scan_{{ fecha }}.csv
      dest: /{{ local_path }}nmap-{{ fecha }}/
    tags:
    - local_directory
  - debug:
      msg: "Copiando archivos a /{{ local_path }}nmap-{{ fecha }}"

  - name: Eliminando evidencia en servidor remoto 
    file:
      path: /{{ remote_path }}{{ ansible_fqdn }}_scan_{{ fecha }}.csv
      state: absent
    tags:
    - delete_remote
  - debug:
      msg: "Eliminando evidencia en servidor remoto"

  - name: Eliminando archivo de puertos.csv
    file:
      path: /tmp/puertos.csv
      state: absent
    tags:
    - delete_remote
  - debug:
      msg: "Eliminando evidencia en servidor remoto"

  - name: Crea_reporte_conjunto
    local_action:
      module: shell echo "Origen,Destination,Port,Protocol,Service,State" >/{{ local_path }}nmap-{{ fecha }}/all.csv && cat /{{ local_path }}nmap-{{ fecha }}/*csv  | grep -v "Origen" >> /{{ local_path }}nmap-{{ fecha }}/all.csv && chmod 777 /{{ local_path }}nmap-{{ fecha }}/*csv 
    tags:
    - full_report
  - debug:
      msg: "Creando reporte global en /{{ local_path }}nmap-{{ fecha }}/all.csv"